# Generated by Django 4.2 on 2024-01-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': '品牌表',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='categorize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categorize_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '分类表',
                'db_table': 'categorize',
            },
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture_name', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': '图片表',
                'db_table': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': '标签表',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='invent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, default=0)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('motes', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorting', to='IMS.categorize')),
                ('picture', models.ManyToManyField(blank=True, to='IMS.picture')),
                ('tag', models.ManyToManyField(blank=True, to='IMS.tag')),
            ],
            options={
                'verbose_name': '库存表',
                'db_table': 'invent',
            },
        ),
    ]
