# Generated by Django 4.2 on 2024-01-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invent',
            new_name='goods',
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '货物表'},
        ),
    ]
