# Generated by Django 4.2 on 2024-01-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_alter_brand_options_alter_categorize_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='motes',
        ),
        migrations.AddField(
            model_name='goods',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='categorize',
            name='categorize_text',
            field=models.CharField(max_length=100, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorting', to='IMS.categorize', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='货品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='num',
            field=models.IntegerField(blank=True, default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ManyToManyField(blank=True, to='IMS.picture', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tag',
            field=models.ManyToManyField(blank=True, to='IMS.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='标签'),
        ),
    ]
