# Generated by Django 4.2 on 2024-01-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0005_remove_goods_motes_goods_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sorting', to='IMS.categorize', verbose_name='分类'),
        ),
    ]
