# Generated by Django 4.2 on 2024-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0006_alter_goods_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='sorting', to='IMS.categorize', verbose_name='分类'),
        ),
    ]
