# Generated by Django 4.2 on 2024-01-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0007_remove_goods_category_goods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='sorting', to='IMS.categorize', verbose_name='分类'),
        ),
    ]
