# Generated by Django 4.2 on 2024-01-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0008_alter_goods_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorting', to='IMS.categorize', verbose_name='分类'),
        ),
    ]
